name: notoro
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  fl_chart: ^0.70.2
  equatable: ^2.0.7
  provider: ^6.1.4
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/branding/
    - assets/body_parts/
    - assets/exercises/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/app_logo.png"






























