name: notoro
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  freezed: ^3.0.6
  equatable: ^2.0.7
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/app_logo.png"






























